### ISSUE TITLE
Error while compiling

### ISSUE THREAD

**Issue by jeffreyvanhees** [januslo/react-native-bluetooth-escpos-printer#1]
Hi, seems a nice package! Unfortunately i've got an error while compiling the package:

`> Task :react-native-bluetooth-escpos-printer:compileDebugJavaWithJavac FAILED
/Users/jeffreyvanhees/Projects/emeals_terminal/node_modules/react-native-bluetooth-escpos-printer/android/src/main/java/cn/jystudio/bluetooth/tsc/TscCommand.java:372: error: cannot find symbol
    public void add1DBarcode(int x, int y, BARCODETYPE type, int height, READABEL readable, ROTATION rotation,
                                                                         ^
  symbol:   class READABEL
  location: class TscCommand
/Users/jeffreyvanhees/Projects/emeals_terminal/node_modules/react-native-bluetooth-escpos-printer/android/src/main/java/cn/jystudio/bluetooth/tsc/RNBluetoothTscPrinterModule.java:190: error: cannot find symbol
    private TscCommand.READABEL findReadable(int readable) {
                      ^
  symbol:   class READABEL
  location: class TscCommand
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: /Users/jeffreyvanhees/Projects/emeals_terminal/node_modules/react-native-bluetooth-escpos-printer/android/src/main/java/cn/jystudio/bluetooth/tsc/TscCommand.java uses unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
2 errors`

FAILURE: Build failed with an exception.

**Comment by januslo** [comment]
Hi, @jeffreyvanhees I am still working at this lib. the iOS is not work now, And the APIs may change during the developing.

**Comment by jeffreyvanhees** [comment]
Hi @januslo,

Thanks for fixing. Also  another error on Android:

`RNBluetoothTscPrinterModule.java:190: error: cannot find symbol
    private TscCommand.READABEL findReadable(int readable) {
                      ^
  symbol:   class READABEL
  location: class `TscCommand``

Should be great if I can use this package in the feature!

**Comment by januslo** [comment]
@jeffreyvanhees  sorry about that. fixed and tested with examples.

**Comment by playmobilman** [comment]
Hi @januslo, really liked your module, but I'm getting an issue when trying to print to a Zebra iMZ320 Bluetooth printer, when I press any PRINT button inside the examples app, I can see the blue bluetooth light working on the printer but without printing anything.
It is really such a great package and if you could help me I would really appreciate it.
Regards!

**Comment by januslo** [comment]
Maybe you can try to print a simple text to validate the package firstly. I am sorry I got no Zebra devices for testing

发自我的 iPhone

**Comment by playmobilman** [comment]
Thanks @januslo for your suggestion, also can you guide me on how to use this module on an empty app?
Regards!

**Comment by januslo** [comment]
@playmobilman create a RN project, install this plugin and includes the managers as the same as my demo. Then you can try the futures which you need.

**Comment by januslo** [comment]
compiling issue fixed.
