### ISSUE TITLE
can't scale the size of image

### ISSUE THREAD

**Issue by byteab** [januslo/react-native-bluetooth-escpos-printer#104]
I want to print an image with full width. but as I increase the width property, nothing change in print

**Comment by byteab** [comment]
I just fix it by commenting this line of codes in
```
 @ReactMethod
    public void printPic(String base64encodeStr, @Nullable  ReadableMap options) {
        ............


        //cannot larger then devicesWith;
        // if(width > deviceWidth || width == 0){
            // width = deviceWidth;
        // }
}
```
 in 
`node_modules/react-native-bluetooth-escpos-printer/android/src/main/java/cn/jystudio/bluetooth/escpos/RNBluetoothEscposPrinterModule.java`

**Comment by OhFarhan** [comment]
@TheEhsanSarshar you just saved my day bro Jazakallah
