### ISSUE TITLE
About Installation with ios app could not file .podspec file

### ISSUE THREAD

**Issue by pankaj2k9** [januslo/react-native-bluetooth-escpos-printer#105]
<img width="1392" alt="Screenshot at Apr 12 22-29-32" src="https://user-images.githubusercontent.com/13047808/79074665-835b4680-7d0f-11ea-9743-7eb35cc541aa.png">
Could You help why I am getting this type of issue? Did i put the RNBluetoothEscposPrinter.podspec and RNBluetoothEscposPrinter.m in correct directory?

**Comment by roshancaxigo** [comment]
How did you solve this issue ?

**Comment by Madhuri-Bourasi** [comment]
Please let me know how to resolve this issue
