### ISSUE TITLE
Build error

### ISSUE THREAD

**Issue by ragozin-n** [januslo/react-native-bluetooth-escpos-printer#12]
FAILURE: Build failed with an exception.

* What went wrong:
Could not resolve all files for configuration ':app:debugRuntimeClasspath'.
> Could not find any version that matches com.facebook.react:react-native:0.55+.
  Versions that do not match:
      0.20.1
      0.20.0
      0.19.1
      0.19.0
      0.18.0
      + 13 more

"react": "16.6.1",
"react-native": "0.57.5",

**Comment by januslo** [comment]
duplicate with https://github.com/januslo/react-native-bluetooth-escpos-printer/issues/5
