### ISSUE TITLE
Epson printer model

### ISSUE THREAD

**Issue by chaohuichen** [januslo/react-native-bluetooth-escpos-printer#148]
Hi, 

Thank you for developing this great library and I am currently working on a project with react-native connect to a thermal printer. I think this library can help me and I am wondering which Epson or printer should I have in order to use this library, I read the whole document but doesn't seem there is a place for the device's information.

Ps: this maybe not an issue but I just want to get in touch with you guys and feel free to contact me by my email:chenpeter51@gmail.com

Thank you all!

**Comment by tr3v3r** [comment]
@chaohuichen 
Here the list of supported printers I suppose:
![image](https://user-images.githubusercontent.com/23724142/109204880-f4380f80-77b6-11eb-84e9-d1b4e92eba28.png)


But I'm not sure that this library supports them all.
Recently I've wrapped the native Epson SDK so you can give it a try here 
https://github.com/tr3v3r/react-native-esc-pos-printer

It also provides a Bluetooth connection.

**Comment by chaohuichen** [comment]
> @chaohuichen
> Here the list of supported printers I suppose:
> ![image](https://user-images.githubusercontent.com/23724142/109204880-f4380f80-77b6-11eb-84e9-d1b4e92eba28.png)
> 
> But I'm not sure that this library supports them all.
> Recently I've wrapped the native Epson SDK so you can give it a try here
> https://github.com/tr3v3r/react-native-esc-pos-printer
> 
> It also provides a Bluetooth connection.

Thank you!  I really appreciated it.
