### ISSUE TITLE
Can't create handler inside thread that has not called Looper.prepare()

### ISSUE THREAD

**Issue by ragozin-n** [januslo/react-native-bluetooth-escpos-printer#15]
Hi again! :smile: 
I do all stuff that you mentioned in #14 
Finally build is success!

But in 
```
"react": "16.7.0",
"react-native": "0.57.8",
```

Have this error:
![error](https://user-images.githubusercontent.com/16084744/50512921-a0d2b580-0ab6-11e9-93d6-651d77ffd91c.png)

**Comment by januslo** [comment]
That maybe a code error... but, I cannot try to test bluetooth services in the emulator or devices without bluetooth. Thx for your finding.

**Comment by januslo** [comment]
hmmmm.. I will fix it later.

**Comment by januslo** [comment]
fixed in version 0.0.4
