### ISSUE TITLE
Text split

### ISSUE THREAD

**Issue by ragozin-n** [januslo/react-native-bluetooth-escpos-printer#19]
Hi! How make text split in two columns, like
```
<View style={{flexDirection: 'row', justifyContent:'space-between', flex:1}}/>
  <Text>1</Text>
  <Text>2</Text>
</View>
```

I use this code:
```javascript
const textConfig = {
      encoding: 'UTF-8',
      codepage: 0,
      widthtimes: 0,
      heigthtimes: 0,
      fonttype: 0
    }

BluetoothEscposPrinter.printerAlign(BluetoothEscposPrinter.ALIGN.LEFT)
BluetoothEscposPrinter.printText('1:', textConfig)
BluetoothEscposPrinter.printerAlign(BluetoothEscposPrinter.ALIGN.RIGHT)
BluetoothEscposPrinter.printText('2', textConfig)
BluetoothEscposPrinter.printText('\n', textConfig)
```
But get
1:2 aligned to right side of paper

![align](https://user-images.githubusercontent.com/16084744/50633479-41205280-0f6d-11e9-8fc5-ae8eb9acb3e4.png)

**Comment by januslo** [comment]
Printcloumn

发自我的 iPhone

**Comment by januslo** [comment]
> printColumn(ReadableArray columnWidths,ReadableArray columnAligns,ReadableArray columnTexts,ReadableMap options)
> 
> print texts in column, Parameters as following:
> 
> columnWidths => int arrays, configs the width of each column, calculate by english character length. ex:the width of "abcdef" is 5 ,the width of "中文" is 4.
> columnAligns => arrays, alignment of each column, values is the same of printerAlign().
> columnTexts => arrays, the texts of each colunm to print.
> options => text print config options, the same of printText() options.

**Comment by ragozin-n** [comment]
Nah, didn't work
<img width="544" alt="code" src="https://user-images.githubusercontent.com/16084744/50761979-87d3bc80-128d-11e9-8f3f-3d087508112f.png">

Result is:
<img width="216" alt="result" src="https://user-images.githubusercontent.com/16084744/50762005-9f12aa00-128d-11e9-9e5e-882d31fc75b8.png">

Maybe simply add to print \n next line after column?

**Comment by januslo** [comment]
Are you trying to printing a footer which align right?

发自我的 iPhone

**Comment by ragozin-n** [comment]
> Are you trying to printing a footer which align right? 发自我的 iPhone
> […](#)
> 在 2019年1月7日，下午6:05，ragozin-n ***@***.***> 写道： Nah, didn't work Result is: Maybe simply add to print \n next line after column? — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or mute the thread.

No, simple line with one part of text is aligned to left, and second to right side of paper.
I use array with {name, value} objects.
Name: Value

=========== is spacer between lines to test

**Comment by januslo** [comment]
> Nah, didn't work
> <img alt="code" width="544" src="https://user-images.githubusercontent.com/16084744/50761979-87d3bc80-128d-11e9-8f3f-3d087508112f.png">
> 
> Result is:
> <img alt="result" width="216" src="https://user-images.githubusercontent.com/16084744/50762005-9f12aa00-128d-11e9-9e5e-882d31fc75b8.png">
> 
> Maybe simply add to print \n next line after column?




Sorry? What's the problem? You align left in the first column, so while wrap, the char would print at the start of let, you align right in the second column, so the chars in the next lines would just go to the right side. The alignment of each column effects the column itself .

**Comment by januslo** [comment]
Or you post a design of your are going to print, I me check whether can be implemented .

**Comment by januslo** [comment]
I think you are going to print this:
```javascript
let columnWidths = [16, 1, 16];
let textAlignment = [BluetoothEscposPrinter.ALIGN.RIGHT,
 BluetoothEscposPrinter.ALIGN.CENTER,
BluetoothEscposPrinter.ALIGN.LEFT];
let texts = ["this is a name", ":", "like this on right"];
 await  BluetoothEscposPrinter.printColumn(columnWidths, textAlignment, texts, {});
texts = ["this is a name2", ":", "like this on right2"];
 await  BluetoothEscposPrinter.printColumn(columnWidths, textAlignment, texts, {});
texts = ["this is a very long long long long name", ":", "like this on right"];
 await  BluetoothEscposPrinter.printColumn(columnWidths, textAlignment, texts, {});
texts = ["name", ":", "like this on long long long long right"];
```

your may try to split to 3 columns and put the comma on the middle.

**Comment by ragozin-n** [comment]
> let columnWidths = [16, 1, 16]; let textAlignment = [BluetoothEscposPrinter.ALIGN.RIGHT, BluetoothEscposPrinter.ALIGN.CENTER, BluetoothEscposPrinter.ALIGN.LEFT]; let texts = ["this is a name", ":", "like this on right"]; await BluetoothEscposPrinter.printColumn(columnWidths, textAlignment, texts, {}); texts = ["this is a name2", ":", "like this on right2"]; await BluetoothEscposPrinter.printColumn(columnWidths, textAlignment, texts, {}); texts = ["this is a very long long long long name", ":", "like this on right"]; await BluetoothEscposPrinter.printColumn(columnWidths, textAlignment, texts, {}); texts = ["name", ":", "like this on long long long long right"];

I think maybe solution is this?
```javascript
let columnWidths = [16, 1, 16];
let textAlignment = [BluetoothEscposPrinter.ALIGN.RIGHT,
BluetoothEscposPrinter.ALIGN.CENTER,
BluetoothEscposPrinter.ALIGN.LEFT];
let texts = ["Name:", " ", "value"];
await  BluetoothEscposPrinter.printColumn(columnWidths, textAlignment, texts, {});
```

**Comment by ragozin-n** [comment]
According to your docs:
`columnWidths => int arrays, configs the width of each column, calculate by english character length. ex:the width of "abcdef" is 5`

But 'abcdef' length is 6, not 5. Or I need make
```
line.name.length - 1
```
in columns width setup?

**Comment by januslo** [comment]
Plz use the actual length, I will fix the readme 

发自我的 iPhone

**Comment by januslo** [comment]
Emmm,I think you should use fixed length in you case, or it would not adds the spaces automatically.

发自我的 iPhone

**Comment by ragozin-n** [comment]
I add + 1 for both
<img width="591" alt="2019-01-08 15 00 20" src="https://user-images.githubusercontent.com/16084744/50823609-2f1c2680-1356-11e9-82df-5c1ecc63d3dd.png">

 and get this:
<img width="462" alt="2019-01-08 15 00 07" src="https://user-images.githubusercontent.com/16084744/50823566-1a3f9300-1356-11e9-8e82-76afee48673c.png">

For now don't understand how it works 😄

**Comment by ragozin-n** [comment]
> Emmm,I think you should use fixed length in you case, or it would not adds the spaces automatically. 发自我的 iPhone

Like split in two columns with 16 width? 16 + 16 = 32. With 0 fontType this is maximum length.

**Comment by ragozin-n** [comment]
Yes, solve it by inserting spaces between two strings.
