### ISSUE TITLE
TypeError: null is not an object (evaluating 'BluetoothTscPrinter.DIRECTION = { FORWARD: 0, BACKWARD: 1 }')

### ISSUE THREAD

**Issue by Magnetka-dev** [januslo/react-native-bluetooth-escpos-printer#196]
Hi, I'm getting following error:
TypeError: null is not an object (evaluating 'BluetoothTscPrinter.DIRECTION = {
    FORWARD: 0,
    BACKWARD: 1
  }')
Solution with modifying library files here: [https://github.com/januslo/react-native-bluetooth-escpos-printer/issues/94](url) did not work and owner suggests to run on physical device which is exactly what I do and this error is still here. Running on physical android devide.
Thanks.

**Comment by CorentinHeroux** [comment]
Same for me, 'BluetoothTscPrinter.DIRECTION = { FORWARD: 0, BACKWARD: 1 }'), Iphone 11 pro
