### ISSUE TITLE
A problem occurred configuring project ':react-native-bluetooth-escpos-printer'

### ISSUE THREAD

**Issue by asd123456789asdad** [januslo/react-native-bluetooth-escpos-printer#204]
<img width="758" alt="image" src="https://user-images.githubusercontent.com/25948710/187423679-a4a3d40f-7311-4722-b246-cb9e64a89386.png">

I just, install using NPM,
but after that I try to run an error shown like

**Comment by Gokulselvan** [comment]
Hii,

This is because of protocol mismatch in node_modules/react-native-bluetooth-escpos-printer/android/build.gradle


Replace http:// link with https:// will solve this issue.


Edit: Also don't forgot to remove this line compile fileTree(dir: 'libs', include: ['*.jar'])

**Comment by Gokulselvan** [comment]
Hope this also helps 


https://github.com/januslo/react-native-bluetooth-escpos-printer/issues/198

**Comment by asd123456789asdad** [comment]
thanks @Gokulselvan  its help me.
but i facing the new problem when i try to link it with this command  ***react-native link react-native-bluetooth-escpos-printer*** 
<img width="635" alt="image" src="https://user-images.githubusercontent.com/25948710/187473433-bf83c357-2e41-4aa9-925c-f7268237b71f.png">

hoping u still help me to solve this one also

**Comment by Gokulselvan** [comment]
From the document, I understand that.

react-native link is for older version (< 0.6)

U don't need to do that for new versions

**Comment by asd123456789asdad** [comment]
works,,
thanks alot
