### ISSUE TITLE
Image not printing from iOS

### ISSUE THREAD

**Issue by DavidStummer** [januslo/react-native-bluetooth-escpos-printer#21]
I am able to print an image from android phone, but when I try from iOS, the printer prints the first few lines of the image, but then stops feeding the paper, and just keeps printing on the same line. I wonder if anyone else has come across this? I actually reproduced this behaviour in some other software that isn't part of this repo, so I am wondering whether it is a printer bug.

Any help would be appreciated! I have attached pic of the result. Ignore the "hi there" that was from a previous test.

![whatsapp image 2019-01-09 at 23 15 02](https://user-images.githubusercontent.com/4497624/50935612-7e507d00-1464-11e9-80a0-d6a6685a6e51.jpeg)

**Comment by januslo** [comment]
Have you try any other pictures?

发自我的 iPhone

**Comment by DavidStummer** [comment]
Yeh I have, same result :-(

**Comment by DavidStummer** [comment]
I tried with the nyearprint app and it works

**Comment by januslo** [comment]
so  what's the problem? nyearprint not meet your requirement ?

**Comment by DavidStummer** [comment]
I need to create my own custom app. I am desperately trying to print images from iOS using your code but it doesn't work. It works on Android. On iOS the printer appears to get stuck when printing an image. Can you print images from iOS app?

**Comment by DavidStummer** [comment]
I tried to create the simplest image (a black square) and it still doesn't work. I have attached it.
![blacksquare](https://user-images.githubusercontent.com/4497624/50961780-89d19180-14c0-11e9-84a5-d937c6546035.gif)

**Comment by DavidStummer** [comment]
FYI I fixed my issue by implementing a different esc/pos command for printing an image: 

<img width="1173" alt="screenshot 2019-01-15 at 09 21 32" src="https://user-images.githubusercontent.com/4497624/51170697-f7a60080-18a6-11e9-856d-d2e572a9f63a.png">

I already had this code for android (https://www.jianshu.com/p/c0b6d1a4823b) and it was a relatively simple matter of converting over to objective-c.

**Comment by firdaussoberi** [comment]
Hi @DavidStummer , I have exact issue like yours (except my printPic won't print any image and just got stuck there).

Could you elaborate more on how you managed to get past the issue? I'm interested in how you implement that different esc/pos command for iOS.

Thanks!

**Comment by FazilMuhammed** [comment]
@firdaussoberi @DavidStummer hello guys please help how to print Image on Bluetooth thermal printer in IPhone. please help me how its obtain or share your code please. i lost couple months behind this

**Comment by muhamadnabila** [comment]
Hi, I tried some printing function from repository (example folder) but I couldn't try print image, it said error in bad base64. But another printing function is success. only error on print image. Can someone help? (this is android not IOS)

**Comment by yosukapro** [comment]
Hello
Did anyone found solution for this?
I am stuck when try to use printPic method on iOS. For others method it work well.
I am sure base64 format is correct.
The error code return when call printPic method: COMMAND_NOT_SENT, and I call 2 method in same time with printText and printPic but for printText it working.

Information:
react-native: 0.68.7
react-native-bluetooth-escpos-printer: "^0.0.5"
