### ISSUE TITLE
Having bug when Manual linking (Android)

### ISSUE THREAD

**Issue by nguyenthanhan201** [januslo/react-native-bluetooth-escpos-printer#215]
![image](https://user-images.githubusercontent.com/80932055/218237890-5561b058-c86c-4e7a-a8f4-8ad15406cf82.png)

FAILURE: Build failed with an exception.

What went wrong:
A problem occurred configuring project ':react-native-bluetooth-escpos-printer'.
Could not determine the dependencies of null.
Could not resolve all dependencies for configuration ':react-native-bluetooth-escpos-printer:classpath'.
Using insecure protocols with repositories, without explicit opt-in, is unsupported. Switch Maven repository 'BintrayJCenter(http://jcenter.bintray.com/)' to redirect to a secure protocol (like HTTPS) or allow insecure protocols. See https://docs.gradle.org/7.3.3/dsl/org.gradle.api.artifacts.repositories.UrlArtifactRepository.html#org.gradle.api.artifacts.repositories.UrlArtifactRepository:allowInsecureProtocol for more 
details.

I  had this bug when i ran: yarn android

**Comment by nguyenthanhan201** [comment]
https://www.youtube.com/watch?v=ABNmLKrhYdY. i solved this problem (this video helped me)

**Comment by dngns** [comment]
nice for helping me, save my day bro
