### ISSUE TITLE
Can not search device to connect and cannot turn on bluetooth with library ios

### ISSUE THREAD

**Issue by voanhtuan318** [januslo/react-native-bluetooth-escpos-printer#22]

**Comment by januslo** [comment]
You may need to remember the connected device yourself.  ios cannot manage the Bluetooth by app itselft. 

发自我的 iPhone

**Comment by januslo** [comment]
Scanning in iOS should be ok, if there is a problem with that, plz let me know. Turning on/off bluetooth within App is not allowed be Apple, so don't think about this this feather works in iOS.
