### ISSUE TITLE
How to use this in the latest expo framework

### ISSUE THREAD

**Issue by detanx** [januslo/react-native-bluetooth-escpos-printer#251]
[package.json](https://github.com/januslo/react-native-bluetooth-escpos-printer/files/15281983/package.json)

**when I run `eas build -p android --profile development` build fail** 

![image](https://github.com/januslo/react-native-bluetooth-escpos-printer/assets/22371912/ed40a531-6a3b-4882-af2b-f62e711b329b)

**I need help solving this problem quickly.**

**Comment by detanx** [comment]
In [this project](https://github.com/januslo/react-native-bluetooth-escpos-printer), I added some fixes to this repository to make it work for expo on Android. This [demo in here](https://github.com/detanx/expo-react-native-bluetooth-escpos-printer)

**Comment by VPass-V3** [comment]
Will it work for iOS as well?
