### ISSUE TITLE
COMPATIBLE PRINTERS

### ISSUE THREAD

**Issue by suarezkrac** [januslo/react-native-bluetooth-escpos-printer#26]
HI I need buy a printer to connect with the plugin, do you have a list of recommended printers? or maybe one of this is compatible?:

Option 1:

https://www.amazon.com/dp/B074FT268S/ref=sspa_dk_detail_7?psc=1&pd_rd_i=B074FT268S&pd_rd_w=1xZay&pf_rd_p=f0dedbe2-13c8-4136-a746-4398ed93cf0f&pd_rd_wg=dUCss&pf_rd_r=XK9KHX4AKV02J53X9T3E&pd_rd_r=61188285-26f5-11e9-a720-93fce9026ffb

Other Options:

https://www.amazon.com/dp/B079HQJDS8/ref=psdc_6684132011_t4_B0775TBS6Z

https://www.amazon.com/dp/B079HMNG48/ref=psdc_6684132011_t2_B079HQJDS8

https://www.amazon.com/dp/B07FXL932M/ref=sspa_dk_detail_4?psc=1&pd_rd_i=B07FXL932M&pd_rd_w=C8NJ2&pf_rd_p=f0dedbe2-13c8-4136-a746-4398ed93cf0f&pd_rd_wg=TxuKY&pf_rd_r=4WY60GEKKFYFFTWB7JF6&pd_rd_r=0c40ff9d-26f5-11e9-a6ca-87394bc783d5

**Comment by januslo** [comment]
actually I am works at few device, so I cannot provide any supported devices list. Sorry about that.
