### ISSUE TITLE
error

### ISSUE THREAD

**Issue by GuoJiKaiHehe** [januslo/react-native-bluetooth-escpos-printer#3]
Could not resolve all files for configuration ':app:debugRuntimeClasspath'.
> Could not find any version that matches com.facebook.react:react-native:0.55+.
  Versions that do not match:
      0.20.1
      0.20.0
      0.19.1
      0.19.0
      0.18.0
      + 13 more
  Searched in the following locations:
      file:/Users/i/Library/Android/sdk/extras/m2repository/com/facebook/react/react-native/maven-metadata.xml
      file:/Users/i/Library/Android/sdk/extras/m2repository/com/facebook/react/react-native/
      file:/Users/i/Library/Android/sdk/extras/google/m2repository/com/facebook/react/react-native/maven-metadata.xml
      file:/Users/i/Library/Android/sdk/extras/google/m2repository/com/facebook/react/react-native/
      file:/Users/i/Library/Android/sdk/extras/android/m2repository/com/facebook/react/react-native/maven-metadata.xml
      file:/Users/i/Library/Android/sdk/extras/android/m2repository/com/facebook/react/react-native/
      https://jitpack.io/com/facebook/react/react-native/maven-metadata.xml
      https://jitpack.io/com/facebook/react/react-native/
      https://maven.google.com/com/facebook/react/react-native/maven-metadata.xml
      https://maven.google.com/com/facebook/react/react-native/
      https://oss.sonatype.org/content/repositories/snapshots/com/facebook/react/react-native/maven-metadata.xml
      https://oss.sonatype.org/content/repositories/snapshots/com/facebook/react/react-native/
      https://dl.google.com/dl/android/maven2/com/facebook/react/react-native/maven-metadata.xml
      https://dl.google.com/dl/android/maven2/com/facebook/react/react-native/
      file:/Users/i/.m2/repository/com/facebook/react/react-native/maven-metadata.xml
      file:/Users/i/.m2/repository/com/facebook/react/react-native/
      https://jcenter.bintray.com/com/facebook/react/react-native/maven-metadata.xml
      file:/Users/i/fuwuqi/works/eryiSY/node_modules/react-native/android/com/facebook/react/react-native/maven-metadata.xml
  Required by:
      project :app > project :react-native-bluetooth-escpos-printer

**Comment by januslo** [comment]
It's not the plugin issue, plz make sure the react-native version is up to 0.55 and configs the maven repostory to fetch that.

I can found one here:
https://mvnrepository.com/artifact/com.facebook.react/react-native?repo=springio-plugins-release

Em... for this problem, i am quire sure it's a base usage problem or RN , not the bug of this plugin.

**Comment by januslo** [comment]
ah，中国人，你或者看看这个可能就知道是什么问题了 https://github.com/facebook/react-native/issues/8174

**Comment by januslo** [comment]
Or you may see this fork : https://github.com/catnuxer/react-native-bluetooth-escpos-printer
