### ISSUE TITLE
Error trying to make apk: Execution failed for task ':react-native-bluetooth-escpos-printer:verifyReleaseResources'

### ISSUE THREAD

**Issue by fnaquira** [januslo/react-native-bluetooth-escpos-printer#30]
I am getting an error when trying to build the project
![imagen](https://user-images.githubusercontent.com/2091780/53507975-eac02380-3a86-11e9-8699-8174cfa873fd.png)
This error doesnt show when it runs on the phone or the emulator, only when trying to make the apk.
This is my actual setup
![imagen](https://user-images.githubusercontent.com/2091780/53508056-0c210f80-3a87-11e9-9ad6-d58cbc071f3b.png)

**Comment by firdaussoberi** [comment]
I also had this error and resolved it before. I think it comes from the old gradle used in the library.
In in node_modules/ipay88-sdk/android/build.gradle: 
```
        classpath 'com.android.tools.build:gradle:2.3.2'
```
I changed it to 3.2.1 because my build in android folder (android/build.gradle) was something like:
```
...
buildscript {
    ext {
        buildToolsVersion = "28.0.3"
        minSdkVersion = 16
        compileSdkVersion = 27
        targetSdkVersion = 26
        supportLibVersion = "27.1.1"
    }
    repositories {
        google()
        jcenter()
        mavenCentral()
    }
    dependencies {
        classpath 'com.android.tools.build:gradle:3.2.0'

        // NOTE: Do not place your application dependencies here; they belong
        // in the individual module build.gradle files
    }
}
...
```

You also need to change then in node_modules/ipay88-sdk/android/gradle/wrapper/gradle-wrapper.properties
```
distributionUrl=https\://services.gradle.org/distributions/gradle-3.3-all.zip
```

My android/./gradle/wrapper/gradle-wrapper.properties:
```
distributionUrl=https\://services.gradle.org/distributions/gradle-4.10.2-all.zip
```

Don't forget to add in node_modules/ipay88-sdk/android/build.gradle
```
buildscript {
    repositories {
        jcenter()
        google(). //<---add this
    }
...
repositories {
    mavenCentral()
    google() //<--add this
}
```

**Comment by januslo** [comment]
thx @firdaussoberi , and it should work.

**Comment by leanhforevo** [comment]
@firdaussoberi i can’t found module ipay88-sdk in node_modules

**Comment by nikhilsquareboat** [comment]
@firdaussoberi  where is gradle-wrapper.properties i am unable to find it.?

**Comment by nikhilsquareboat** [comment]
> gradle-wrapper.properties

in gradle-wrapper.properties  when i change distributionUrl, getting error
Build failing with 'Could not find method google() for arguments [] on repository container' but i have added google(). please help i am not getting any what is going wrong

**Comment by firdaussoberi** [comment]
@nikhilsquareboat What's your main app android/gradle/wrapper/gradle-wrapper.properties?
For build:gradle:3.2.1 it should look like this:

```bash
distributionBase=GRADLE_USER_HOME
distributionPath=wrapper/dists
distributionUrl=https\://services.gradle.org/distributions/gradle-4.10.2-all.zip
zipStoreBase=GRADLE_USER_HOME
zipStorePath=wrapper/dists
```

**Comment by mrhandoko** [comment]
I added _subproject_ in `android/build.gradle` and it works with build tools version 28.0.3.
Let me know if you've already solved this @firdaussoberi @januslo 

```
buildscript {
    ext {
        buildToolsVersion = "28.0.3"
        minSdkVersion = 16
        compileSdkVersion = 28
        targetSdkVersion = 28
        supportLibVersion = "28.0.0"
    }
    repositories {
        google()
        jcenter()
    }
    dependencies {
        classpath("com.android.tools.build:gradle:3.4.0")
        classpath 'com.google.gms:google-services:4.2.0'
    }
}

allprojects {
    repositories {
        mavenLocal()
        google()
        jcenter()
        maven { url "https://jitpack.io" }
        maven { url "https://maven.google.com" }
        maven {
            // All of React Native (JS, Obj-C sources, Android binaries) is installed from npm
            url "$rootDir/../node_modules/react-native/android"
        }
    }
}

// ###########
subprojects {  // <-- Add this line
    afterEvaluate {project ->
        if (project.hasProperty("android")) {
            android {
                compileSdkVersion 28
                buildToolsVersion '28.0.3'
            }
        }
    }
}
```

**Comment by brilly4n** [comment]
:'(

**Comment by michaelVictoriaDev** [comment]
@mrhandoko  
solved my issue.
> I added _subproject_ in `android/build.gradle` and it works with build tools version 28.0.3.
> Let me know if you've already solved this @firdaussoberi @januslo
> 
> ```
> buildscript {
>     ext {
>         buildToolsVersion = "28.0.3"
>         minSdkVersion = 16
>         compileSdkVersion = 28
>         targetSdkVersion = 28
>         supportLibVersion = "28.0.0"
>     }
>     repositories {
>         google()
>         jcenter()
>     }
>     dependencies {
>         classpath("com.android.tools.build:gradle:3.4.0")
>         classpath 'com.google.gms:google-services:4.2.0'
>     }
> }
> 
> allprojects {
>     repositories {
>         mavenLocal()
>         google()
>         jcenter()
>         maven { url "https://jitpack.io" }
>         maven { url "https://maven.google.com" }
>         maven {
>             // All of React Native (JS, Obj-C sources, Android binaries) is installed from npm
>             url "$rootDir/../node_modules/react-native/android"
>         }
>     }
> }
> 
> // ###########
> subprojects {  // <-- Add this line
>     afterEvaluate {project ->
>         if (project.hasProperty("android")) {
>             android {
>                 compileSdkVersion 28
>                 buildToolsVersion '28.0.3'
>             }
>         }
>     }
> }
> ```

**Comment by 16isaac89** [comment]
i tried every solution here but nothing solves the error and also android/gradle/wrapper/gradle-wrapper.properties does not exist in the package

**Comment by 16isaac89** [comment]
this is my android/build.gradle
// Top-level build file where you can add configuration options common to all sub-projects/modules.


buildscript {
    ext {
        googlePlayServicesVersion = "15.0.1" // default: "+"
        // firebaseMessagingVersion = "15.0.1" 
        buildToolsVersion = "28.0.3"
        minSdkVersion = 21
        compileSdkVersion = 28
        targetSdkVersion = 28
        supportLibVersion = "28.0.0"
    }
    repositories {
        google()
        jcenter()
        maven { url "https://jitpack.io" } 
        maven { url "https://maven.google.com" } 
    }
    dependencies {
        classpath("com.android.tools.build:gradle:3.5.3")
        classpath('com.google.gms:google-services:4.3.3')
        // NOTE: Do not place your application dependencies here; they belong
        // in the individual module build.gradle files
    }
}

allprojects {
    repositories {
        mavenLocal()
        maven {
            // All of React Native (JS, Obj-C sources, Android binaries) is installed from npm
            url("$rootDir/../node_modules/react-native/android")
        }
        maven {
            // Android JSC is installed from npm
            url("$rootDir/../node_modules/jsc-android/dist")
        }

        google()
        jcenter()
        maven { url 'https://www.jitpack.io' }
    }
}

subprojects {  // <-- Add this line
    afterEvaluate {project ->
        if (project.hasProperty("android")) {
            android {
                compileSdkVersion 28
                buildToolsVersion '28.0.3'
            }
        }
    }
}
but the app closes on opening

**Comment by angelop11** [comment]
any solution? the app closes in install process

**Comment by malzate** [comment]
> google()

it solved my issue, thank u very much
