### ISSUE TITLE
Does it not support Thai language?

### ISSUE THREAD

**Issue by 9wisit** [januslo/react-native-bluetooth-escpos-printer#33]
I want to print to be Thai characters but it doesn't support.

**Comment by 9wisit** [comment]
This problem is solved by setting the encoding to Cp874 and codepage to 255.

### Example Code
`BluetoothEscposPrinter.printText("สวัสดีครับท่านผู้ชม", {encoding: 'Cp874',codepage: 255});`

**Comment by shubhamdeol** [comment]
@petchpool  How you found this encoding? 
I want to have support for English

**Comment by dheeraj85** [comment]
Hi, 
Any solution for Hindi Langauge for encoding and pagecode?
