### ISSUE TITLE
How can I balance the columnWidths?

### ISSUE THREAD

**Issue by 9wisit** [januslo/react-native-bluetooth-escpos-printer#35]
I have tried to print for printing column but the width of columns display wrong.
I want to balance the width of the columns. How can I resolve it?

If you see the example below, You will see the price is not balance.

This is an example that I got.
![s__3907588](https://user-images.githubusercontent.com/32625530/54025095-1308fa00-41cc-11e9-9f6b-b0863394a9dd.jpg)

**Comment by 9wisit** [comment]
This is my code.
![screen shot 2562-03-08 at 18 17 22](https://user-images.githubusercontent.com/32625530/54025866-74ca6380-41ce-11e9-92b4-03fdcd1de327.png)

**Comment by januslo** [comment]
Is it Tai?

发自我的 iPhone

**Comment by 9wisit** [comment]
Yes, It is Thai.

**Comment by 9wisit** [comment]
I have solved this problem already. 
Since the column width is calculated by the length of the characters and the Thai characters is not supported to count the length of Thai floating vowels. It counts consonant only and inline vowels.

So, I solved this problem by creating a method to count Thai floating vowels. 
### Like this
![Screen Shot 2562-03-09 at 12 12 05](https://user-images.githubusercontent.com/32625530/54066580-d0dfc700-4264-11e9-9b4d-c6379c7db96f.png)

And add the counted floating vowel length to the constant width to the column of Thai text.
### Like this
![Screen Shot 2562-03-09 at 12 12 38](https://user-images.githubusercontent.com/32625530/54066614-7e52da80-4265-11e9-809f-c812a4cea7e0.png)

Finally, It should work fine.

**Comment by dumbest** [comment]
@9wisit May I ask what thermal printer brand and model are you using? Does it work on both Android and iOS?
