### ISSUE TITLE
你好，我的QQ：921110219  能加个好友吗，有点问题想请教下

### ISSUE THREAD

**Issue by Leslie-Luo** [januslo/react-native-bluetooth-escpos-printer#39]
你好，我的QQ：921110219  能加个好友吗，有点问题想请教下
![image](https://user-images.githubusercontent.com/22937782/54586555-65fa7100-4a58-11e9-96bf-07474e01410d.png)
![image](https://user-images.githubusercontent.com/22937782/54586587-76aae700-4a58-11e9-8404-0fed69ad54be.png)

**Comment by januslo** [comment]
Demo 项目测试通过的了，你注意一下install 之后要react-native link 


发自我的 iPhone

**Comment by Leslie-Luo** [comment]
我按照你的教程已经执行过react-native link

**Comment by januslo** [comment]
你写错字，label，不是lable
是不是我文档里面错了？
发自我的 iPhone
