### ISSUE TITLE
usb thermal printer

### ISSUE THREAD

**Issue by tareqwaisi** [januslo/react-native-bluetooth-escpos-printer#41]
Hi,
Thanks for your work.
Does the package work with a usb thermal printer?
if not, would you be able to refer me to a proper package?
Thanks

**Comment by januslo** [comment]
Not works with USB，sorry about that

发自我的 iPhone

**Comment by tareqwaisi** [comment]
That's fine. Thanks.

**Comment by v4irajvimu** [comment]
> Not works with USB，sorry about that 发自我的 iPhone
> […](#)
> 在 2019年3月20日，上午4:50，Zagros ***@***.***> 写道： Hi, Thanks for your work. Does the package work with a USB thermal printer? if not, would you be able to refer me to a proper package? Thanks — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or mute the thread.

what about for USB then?
