### ISSUE TITLE
Anyone can help me ? evaluating 'BluetoothTscPrinter.DIRECTION 

### ISSUE THREAD

**Issue by filipecamargo10** [januslo/react-native-bluetooth-escpos-printer#47]
i have this problem 

`undefined is not an object (evaluating 'BluetoothTscPrinter.DIRECTION = {
    FORWARD: 0,
    BACKWARD: 1
  }')
<img width="559" alt="Captura de Tela 2019-05-04 às 19 29 56" src="https://user-images.githubusercontent.com/6546277/57185500-07bc0d00-6ea3-11e9-8e70-40c95d79cbce.png">

<unknown>
    index.js:5:20
loadModuleImplementation
    require.js:292:12
<unknown>
    SellScreen.js:7:2
loadModuleImplementation
    require.js:292:12
<unknown>
    MainTabNavigator.js:7
loadModuleImplementation
    require.js:292:12
<unknown>
    AppNavigator.js:3
loadModuleImplementation
    require.js:292:12
<unknown>
    App.js:4
loadModuleImplementation
    require.js:292:12
<unknown>
    AppEntry.js:2
loadModuleImplementation
    require.js:292:12
guardedLoadModule
    require.js:179:45
global code
    <unknown file>:0`

**Comment by januslo** [comment]
like #7 . plz make sure the plugin is installed and linked.
