### ISSUE TITLE
Could not find any version that matches com.facebook.react:react-native:0.55+.

### ISSUE THREAD

**Issue by shubhamdeol** [januslo/react-native-bluetooth-escpos-printer#5]
I added this package but getting this error while building and running expo ejected app. Please Help.
otherwise this package looks great

**Comment by januslo** [comment]
plz check here: https://github.com/januslo/react-native-bluetooth-escpos-printer/issues/3#issuecomment-443088001

**Comment by shubhamdeol** [comment]
@januslo  I forked your repo and changed react native version to **implementation 'com.facebook.react:react-native:0.57**

not I am getting same error with this version. Expo uses the fork of react native version 0.57

**Comment by januslo** [comment]
em... I think you may try this : https://github.com/catnuxer/react-native-bluetooth-escpos-printer/commit/dc4c3a8f23a3511f546a4e93f871d4cf827b6019

**Comment by shubhamdeol** [comment]
yes, It it working now, but can not use any method with printer, all async functions are falling in catch block. As it's not related with this issue so closing this one
