### ISSUE TITLE
Location permission in module

### ISSUE THREAD

**Issue by huytran123** [januslo/react-native-bluetooth-escpos-printer#51]
Hi 

When i use your module, app asks me allow location permission. 
I do not know why this module need location permission? please can you give me detail.

I found this code in android module:

int permissionChecked = ContextCompat.checkSelfPermission(reactContext, android.Manifest.permission.ACCESS_COARSE_LOCATION);
            if (permissionChecked == PackageManager.PERMISSION_DENIED) {
                // // TODO: 2018/9/21
                ActivityCompat.requestPermissions(reactContext.getCurrentActivity(),
                        new String[]{android.Manifest.permission.ACCESS_COARSE_LOCATION},
                        1);
            }
Thanks so much

**Comment by shubhamdeol** [comment]
@huytran123  why you closed the issue?

**Comment by fnaquira** [comment]
I have the same issue on a fresh installment, what was the solution @huytran123 ?

**Comment by huytran123** [comment]
@fnaquira : you can read detail: https://developer.android.com/reference/android/bluetooth/le/BluetoothLeScanner
