### ISSUE TITLE
print data from API / JSON

### ISSUE THREAD

**Issue by rafiafmar** [januslo/react-native-bluetooth-escpos-printer#58]
how to print data from api / json?
which calls array data using the fetch function

**Comment by januslo** [comment]
I am not sure what u r asking

发自我的 iPhone

**Comment by rafiafmar** [comment]
like in the example to print a recipe that the value is entered manually:

await BluetoothEscposPrinter.printText ("... \ r \ n", {});

or

await BluetoothEscposPrinter.printColumn (..., [...], [...], ["..."], {};

my question what if the value comes from an API / JSON array data, so the printed data can be automatic?
I call the data array using the fetch function ...
and i use android

**Comment by januslo** [comment]
Sorry， still cannot get it， but we can see a JSON as a js object, or you may need to parse it with with js JSON object. 


发自我的 iPhone

**Comment by rafiafmar** [comment]
sorry, what does it mean to see JSON as a js object?
I have an API / JSON address:
https://skripsiuwp.000webhostapp.com/SFA/keranjang_penjualan.php

can it be printed or at least it can be displayed on the application screen according to the template of the recipe that you are example?

**Comment by januslo** [comment]
sorry are u a programmer? If not, plz ask your programmer to do that


发自我的 iPhone

**Comment by januslo** [comment]
Hmmmm, This is a printing plugin, cannot handle the networks.

发自我的 iPhone

**Comment by rafiafmar** [comment]
thank you for your information
