### ISSUE TITLE
how to printer barcode?

### ISSUE THREAD

**Issue by PhamMinhKha** [januslo/react-native-bluetooth-escpos-printer#59]
printBarCode(String str,int nType, int nWidthX, int nHeight, int nHriFontType, int nHriFontPosition)
please give me a simple code use this code.
I don't know how to pass parameters nType, nHriFontType and nHriFontPosition

**Comment by vikaskbh** [comment]
Try this,
 `await BluetoothEscposPrinter.printBarCode('VIKAS', 73, 3, 100, 0, 2); // barcode`
