### ISSUE TITLE
framesToPop: 1, code: EUNSPECIFIED

### ISSUE THREAD

**Issue by shubhamdeol** [januslo/react-native-bluetooth-escpos-printer#6]
when I am calling 
 BluetoothEscposPrinter.printerAlign(BluetoothEscposPrinter.ALIGN.CENTER)
      .then(() => alert('success')).catch(err => alert(JSON.stringify(err)))

also, function to initialize printer is not found :(

**Comment by januslo** [comment]
Would you plz show the error in detail?


发自我的 iPhone

**Comment by shubhamdeol** [comment]
Okay, I attach a screen shoot soon

**Comment by shubhamdeol** [comment]
Have tested this library with your react native code? 
Does this works with Android. Can you please provide me other alternatives to this. I want to print order details with esc pos printer. Is this possible with https://github.com/Polidea/react-native-ble-plx. This library

**Comment by shubhamdeol** [comment]
Can you share some repo, where you are using these?

**Comment by januslo** [comment]
Sorry, I mean I am using react-native-bluetooth-escpos-printer in my production. So I am sure it can be build and run.

**Comment by shubhamdeol** [comment]
In my case I am getting ** "COMMAND_NOT_SEND"**   
promise fails to this promise.reject("COMMAND_NOT_SEND");

when I am using this method: 

initPrint = async () => {
  await BluetoothEscposPrinter.printerInit()
}

**Comment by januslo** [comment]
@shubhamdeol  COMMAND_NOT_SEND may caused by device was not connected. You need to connect the device with BluteToochManger before sending commands to it

**Comment by shubhamdeol** [comment]
@januslo, okay thanks. Now I guess It will work. Will use it now in production. but one last issue though 
. When I am running **BluetoothTscPrinter.printLable** function. warning comes up with "undefined is not a function". I think you have implemented **BluetoothTscPrinter** package yet. 
all  other commands are working as they are called with **BluetoothEscposPrinter** for Example this **BluetoothEscposPrinter.printText("Hello world\n\r",{});**  works completly fine.

**Comment by fnaquira** [comment]
the function is printLabel, that was a typo
