### ISSUE TITLE
printLabel undefined is not a function

### ISSUE THREAD

**Issue by shubhamdeol** [januslo/react-native-bluetooth-escpos-printer#7]
When I am running **BluetoothTscPrinter.printLable** function. warning comes up with **"undefined is not a function".** I think you have implemented BluetoothTscPrinter package yet.
all other commands are working as they are called with BluetoothEscposPrinter, for Example, this **BluetoothEscposPrinter.printText("Hello world\n\r",{});** works completely fine.[](url)

**Comment by januslo** [comment]
TSC printer works fine. Emmm, what platform you are in, IOS or Android?

发自我的 iPhone

**Comment by shubhamdeol** [comment]
I am on android. I will share my code if you want

**Comment by januslo** [comment]
What Ran version you are working with?

发自我的 iPhone

**Comment by shubhamdeol** [comment]
I am testing on android version 8, and please add manual linking guides as well.

**Comment by januslo** [comment]
Emmm I wanna know the RN version . ESC manager works fine shows the problem not the link issue


发自我的 iPhone

**Comment by shubhamdeol** [comment]
Ohh sorry... I am using expo sdk 31, which is based on React Native 0.57

**Comment by shubhamdeol** [comment]
about:blank

**Comment by shubhamdeol** [comment]
![image](https://user-images.githubusercontent.com/11364449/50159658-3626ba80-02fd-11e9-9249-ae92e3ae17f2.png)

see, here is the screenshoot of warning I am receiving with printLabel. 
and I am passing options as 

```javascript
initPrint = async () => {
    const options = {
        width: 40,
        height: 30,
        gap: 20,
        direction: BluetoothTscPrinter.DIRECTION.FORWARD,
        reference: [0, 0],
        tear: BluetoothTscPrinter.TEAR.ON,
        sound: 0,
        text: [{
            text: 'I am a testing txt',
            x: 20,
            y: 0,
            fonttype: BluetoothTscPrinter.FONTTYPE.SIMPLIFIED_CHINESE,
            rotation: BluetoothTscPrinter.ROTATION.ROTATION_0,
            xscal:BluetoothTscPrinter.FONTMUL.MUL_1,
            yscal: BluetoothTscPrinter.FONTMUL.MUL_1
        },{
            text: '你在说什么呢?',
            x: 20,
            y: 50,
            fonttype: BluetoothTscPrinter.FONTTYPE.SIMPLIFIED_CHINESE,
            rotation: BluetoothTscPrinter.ROTATION.ROTATION_0,
            xscal:BluetoothTscPrinter.FONTMUL.MUL_1,
            yscal: BluetoothTscPrinter.FONTMUL.MUL_1
        }],
        qrcode: [{x: 20, y: 96, level: BluetoothTscPrinter.EEC.LEVEL_L, width: 3, rotation: BluetoothTscPrinter.ROTATION.ROTATION_0, code: 'show me the money'}],
        barcode: [{x: 120, y:96, type: BluetoothTscPrinter.BARCODETYPE.CODE128, height: 40, readable: 1, rotation: BluetoothTscPrinter.ROTATION.ROTATION_0, code: '1234567890'}],
        // image: [{x: 160, y: 160, mode: BluetoothTscPrinter.BITMAP_MODE.OVERWRITE,width: 60,image: base64Image}]
     }
```

**Comment by januslo** [comment]
Sorry，never tested with expo.

**Comment by januslo** [comment]
Here is a real case as a sample :
```javascript
    await BluetoothTscPrinter.printLabel({
                        width: labelConfig.width,
                        height: labelConfig.height,
                        gap: labelConfig.gap,
                        direction: BluetoothTscPrinter.DIRECTION.FORWARD,
                        reference: [0, 0],
                        tear: BluetoothTscPrinter.TEAR.ON,
                        sound: 1,
                        text: texts,
                        barcode: barCode,
                        home:  0
                    });
```
No everything need for printing a label.  further more , printLabel not printlabel

**Comment by shubhamdeol** [comment]
okay, so if I don't want image, and I want barcode only in that case it won't work ?

see, here I am getting this function, but properties like DIRECTION are not getting attached to object may be :(

![image](https://user-images.githubusercontent.com/11364449/50161472-e4346380-0301-11e9-940a-c0a5adaafc7d.png)

**Comment by shubhamdeol** [comment]
see, I found the error, You have this import **import cn.jystudio.bluetooth.tsc.RNBluetoothTscPrinterModule**

in your RNBluetoothEscposPrinterPackage.java file, line number 9, but there is no such file in tsc folder. please add that file if you have

**Comment by raindev32** [comment]
is this issues is fixed ?
