### ISSUE TITLE
Encoding UTF-8

### ISSUE THREAD

**Issue by tranhung148** [januslo/react-native-bluetooth-escpos-printer#8]
I need print some text with encoding UTF-8.
Seem this library  does not support UTF-8.
Is it right?

**Comment by januslo** [comment]
What language you are working with? I have tested English and some Chinese, Both works fine except ¥ siymb 

发自我的 iPhone

**Comment by januslo** [comment]
here is a sample:
![alt](https://github.com/januslo/react-native-bluetooth-escpos-printer/blob/master/examples/sample.jpg)

**Comment by tranhung148** [comment]
i am using vietnamese.
I need write some words: ư, ơ, ă, â, ứ, ớ, ở, ô, ....
In this below example, i am trying write text: "Người". But receive this result.
![48377897_320304195488746_6057643520913571840_n](https://user-images.githubusercontent.com/16429671/50214736-9710ca00-03b3-11e9-95e0-f9ed41695abe.jpg)

**Comment by tranhung148** [comment]
i was try pass param encoding "UTF-8" but didn't receive my expect

**Comment by januslo** [comment]
I found something shows UTF-8 would not resolve vietnamese problem neither. 

https://stackoverflow.com/questions/53099808/convert-text-to-latin-encoding-and-decode-back-problem-for-vietnamese

It need some codding test for vietnamese but I cannot spare my time to it now.

**Comment by guihendias** [comment]
Hey, is there a encoding where I can use the dolar sign? I'm from brazil, utf-8 really isn't working as expected. 

Any thoughts on how can proceed? I need to print phrases like "Preço R$ 5,00" and prints "Pre?o R? 5,00" on encodings i've tried.

thankssss

**Comment by gdierksmeier** [comment]
You can play with SelfText and see if your printer accept the Portuguese....(codepage)
    BluetoothEscposPrinter.printText( "Preço", {
      encoding: 'Cp037',
      codepage: 3,
      widthtimes: 0,
      heigthtimes: 0,
      fonttype: 1
    } );
You can find encoding here:
https://docs.oracle.com/javase/8/docs/technotes/guides/intl/encoding.doc.html

Boa sorte.

**Comment by gdierksmeier** [comment]
![20190129_084039 1](https://user-images.githubusercontent.com/25743679/52278118-4d7e3d80-2967-11e9-81b2-ad1230a0640f.jpg)

**Comment by CanerDumanoglu** [comment]
İ want BluetoothEscposPrinter.printText("İŞÖÇİşiçöğü awd awdawdaad --**? \r\n").
thats turkish characters
which one should I choose encoding and codepage ?

**Comment by gdierksmeier** [comment]
Try this

    BluetoothEscposPrinter.printText( "İŞÖÇİşiçöğü awd awdawdaad --**? \r\n", {
      encoding: 'Cp1254',
      codepage: 22,
      widthtimes: 0,
      heigthtimes: 0,
      fonttype: 1
    } );

Other options:  Cp857, Cp1256, Cp1026

**Comment by CanerDumanoglu** [comment]
@gdierksmeier thanks bro. İm using **codepage 32** with **encoding Cp1254**. Now working all turkish characters.

**Comment by KBepo** [comment]
Hello,
didn't want to make new issue ticket so I'll just ask here. Which encoding should I use for Croatian lagnuage? We are using latinic letters with addition of ć,č,š,ž and đ.

As others mentioned UTF8 or UTF-8 for encoding doesn't seem to work.

Or if you could point me to all the encodings supported so I can test them till I find suitable one.

Best regards,
Bepo.

**Comment by vgvishal538** [comment]
Hello @gdierksmeier can you please tell me which encoding i should use for printing Indian (Hindi ) language?

**Comment by gdierksmeier** [comment]
Sorry @vgvishal538 i have no experience with hindi....seems the solution is convert and print an image...  
https://stackoverflow.com/questions/36645996/how-to-display-hindi-or-gujarati-font-using-bluetooth-printer

**Comment by Iamstanlee** [comment]
hello , which encoding should i use for printing Arabic text ? 

anyone ? please.

**Comment by gdierksmeier** [comment]
We are using:
ENCODING: ISO8859_6
CODEPAGE: 22

All depend of your printer...try also the combinations:
"encoding": "Cp1256" or "encoding":" Cp864"  with CODEPAGE: 22 or 32

**Comment by mg4u** [comment]
@Iamstanlee did you get the Arabic encoding?

**Comment by mg4u** [comment]
The best solution I find out is, Build your receipt in View component and style it as you like, do not forget to make the background of the view "white", and use  "react-native-view-shot" to convert the view to an image then printPic by Bluetooth printer.
Hope this helps.

**Comment by alimasarra** [comment]
hi, its printing arabic, but its printing it in the inverse way, like: علي مسرة its printing it ةرسم يلع
any solution for that?
and i am using these 
ENCODING: ISO8859_6
CODEPAGE: 22

**Comment by alimasarra** [comment]
fixed it by adding this.reverseString before the text

**Comment by mg4u** [comment]
@alimasarra  could you add snippet code?

**Comment by aeolus** [comment]
Need some help with Swedish, anyone got lucky?

**Comment by januslo** [comment]
Have you try to check the codepage information?

发自我的 iPhone

**Comment by datvp09** [comment]
BluetoothEscposPrinter.printText("Tiếng việt nè đm chúng m\n\n", {encoding: 'Cp1258',codepage:30});

@gdierksmeier I found Cp1258 and codepage 30 nearly display Vietnamese characters, are there any option? my device is Mini thermal printer 5802DD

**Comment by quy1403** [comment]
@datvp09  máy in của e là Apos P100, e thử Cp1258 and codepage 30 như bác mà k in đc TV, có cách nào dò ra đc encoding và codepage chuẩn cho máy in của e k bác, thanks uuu

**Comment by datvp09** [comment]
@quy1403 e tìm xem có file pdf guide của máy k, tìm đến phần text code gì đó có list ra 1 loạt encoding rồi từ đó thử codepage

**Comment by billdoorsvn** [comment]
thường ko in đc tiếng việt đâu, vì bản chất cái encoding của thiết bị ko hỗ trợ. bạn nên chuyển solution qua in ảnh. nếu có cả barcode hoặc qr code thì tách ra in nhiều hàm thì mới quét dc.

**Comment by quy1403** [comment]
> thường ko in đc tiếng việt đâu, vì bản chất cái encoding của thiết bị ko hỗ trợ. bạn nên chuyển solution qua in ảnh. nếu có cả barcode hoặc qr code thì tách ra in nhiều hàm thì mới quét dc.

in ảnh thì in chậm với tốn mực hơn đúng ko ạ, có lib nào convert text thành ảnh phục vụ món in nàhy ko bác

**Comment by quy1403** [comment]
> @quy1403 e tìm xem có file pdf guide của máy k, tìm đến phần text code gì đó có list ra 1 loạt encoding rồi từ đó thử codepage
e k tìm đc pdf guide, giờ k biết encoding vs codepage như nào, của a in tiếng việt ngon lành chứ, e đang có 2 máy xprinter và Apos ở đay mà loay hoay ko in đc, à cho e xin Skype có gì chat trao đổi

**Comment by quy1403** [comment]
@datvp09 
e k tìm đc pdf guide, giờ k biết encoding vs codepage như nào, của a in tiếng việt ngon lành chứ, e đang có 2 máy xprinter và Apos ở đay mà loay hoay ko in đc, à cho e xin Skype có gì chat trao đổ

**Comment by quy1403** [comment]
@billdoorsvn  
e thử in 1 cái ảnh thì thấy tốc độ in khá trậm, vs có vẻ khá tốn mực, chứ k vèo vèo như in text a ơi, có cách nào in nhanh như in text k ạ

**Comment by datvp09** [comment]
máy in nhiệt thì làm gì có mực :v 
bên mình dùng sunmi printer r, có thư viện hỗ trợ luôn cho khỏe

**Comment by quy1403** [comment]
@tranhung148  sao lại close thế a ơi, vẫn chưa đc giải quyết mà a

**Comment by quy1403** [comment]
@datvp09  a có skype ko cho e xin với , e hỏi a trực tiếp cho rõ khoản in ấn này ạ, help me please

**Comment by PhamMinhKha** [comment]
Làm sau in được tiếng việt vậy bác @tranhung148

**Comment by shubhamdeol** [comment]
> Hello @gdierksmeier can you please tell me which encoding i should use for printing Indian (Hindi ) language?

@vgvishal538  Have you found any encoding for hindi?

**Comment by huuanh021287** [comment]
Hello.
I have problem printer vietnamese.
Can you help me?

await BluetoothEscposPrinter.printText('Tiếng Việt \r\n\r\n\r\n', {
      encoding: 'GBK',
      codepage: 32, // 27 or 22 or 30. 
      widthtimes: 0,
      heigthtimes: 0,
      fonttype: 0,
    });

Thanks

**Comment by aroumane** [comment]
Hello,
For the euro sign the configuration is this:
```
{
encoding:' Cp858',
codepage: 13
}
```
**for the French language**

**Comment by shushi1506** [comment]
@quy1403 
a đã tìm ra cách in tiếng việt trên con apos p100 chưa ạ, giúp em với

**Comment by tranhung148** [comment]
Không in được tiếng việt có dấu đâu.

Vào 15:24, T.3, 29 Th6, 2021 Bui Tuan Anh ***@***.***> đã
viết:

**Comment by NguyenThanhNhuJS99** [comment]
> Làm sau in được tiếng việt vậy bác @tranhung148



> @datvp09
> e k tìm đc pdf guide, giờ k biết encoding vs codepage như nào, của a in tiếng việt ngon lành chứ, e đang có 2 máy xprinter và Apos ở đay mà loay hoay ko in đc, à cho e xin Skype có gì chat trao đổ

Ra chưa anh ơi, em cũng đang dùng con xprinter ạ. Cứu em với :))

**Comment by PhamMinhKha** [comment]
Chuyển thứ cần in sang image rồi in ra kiểu image là được. Nhược điểm là máy in sẽ in lâu hơn nhưng được cái tiếng việt

**Comment by NguyenThanhNhuJS99** [comment]
> Chuyển thứ cần in sang image rồi in ra kiểu image là được. Nhược điểm là máy in sẽ in lâu hơn nhưng được cái tiếng việt

Cảm ơn anh ạ

**Comment by NguyenThanhNhuJS99** [comment]
> Chuyển thứ cần in sang image rồi in ra kiểu image là được. Nhược điểm là máy in sẽ in lâu hơn nhưng được cái tiếng việt

À anh dùng thư viện gì để chuyển sang image vậy ạ, tks anh

**Comment by shushi1506** [comment]
Máy nào có hỗ trợ tiếng việt thì in được, mình thử 4, 5 con có một con
không hỗ trợ, k tài nào in được, chuyển sang image thì có tiếng việt nhưng
siêu chậm

Vào Th 4, 21 thg 7, 2021 vào lúc 14:12 NguyenThanhNhuJS99 <
***@***.***> đã viết:

**Comment by DDS-VangTA** [comment]
> > Chuyển thứ cần in sang image rồi in ra kiểu image là được. Nhược điểm là máy in sẽ in lâu hơn nhưng được cái tiếng việt
> 
> À anh dùng thư viện gì để chuyển sang image vậy ạ, tks anh

>Load 1 bitmap từ local( nền trắng). Draw text lên bitmap image đó rồi in ra

**Comment by DDS-VangTA** [comment]
> i was try pass param encoding "UTF-8" but didn't receive my expect

@tranhung148 anh đã in được tiếng Việt chưa ạ. Cho e giải pháp với

**Comment by d6mobile** [comment]
e cũng đang gặp vấn đề trên iOS. ko tìm đc encoding hỗ trợ tiếng việt. mn chỉ e với. may xprint (cắm máy tinh in blue thì có hỗ trợ tiếng việt)

**Comment by huuanh1987** [comment]
> BluetoothEscposPrinter.printText("Tiếng việt nè đm chúng m\n\n", {encoding: 'Cp1258',codepage:30});
> 
> @gdierksmeier I found Cp1258 and codepage 30 nearly display Vietnamese characters, are there any option? my device is Mini thermal printer 5802DD

@d6mobile Bác dùng cách này thử xem.
Còn k thì in bằng image thôi, hơi chuối thật.

**Comment by haphanquang** [comment]
mọi người có giải pháp chưa vậy, em đang cần in trên iOS? 
nếu dùng image thì chậm quá, chỉ còn các bỏ dấu rồi in ra nhưng như vậy thì không ổn tí nào.

**Comment by Kunjvr1223** [comment]
Hello @vgvishal538 Have You Found Any Encoding That Print Indian Languages ? Please Tell Me.

**Comment by snowinrain** [comment]
I have a generic solution to print any language, including Vietnamese. It's not perfect but will work definitely.
1) You need to find code page that support your language. E.g.: 27, 30, 31, 32 are known Code Page for Vietnamese.
2) Encoding your text with correct encoder. E.g: TCVN-3 is correct one for Vietnamese.
Please refer to this [link](https://download4.epson.biz/sec_pubs/pos/reference_en/charcode/page_30.html) for more detail.

**Comment by FaizyQadri** [comment]
> We are using: ENCODING: ISO8859_6 CODEPAGE: 22
> 
> All depend of your printer...try also the combinations: "encoding": "Cp1256" or "encoding":" Cp864" with CODEPAGE: 22 or 32

is ur we are getting it as reverse

**Comment by AnhhoangXuan** [comment]
> I need print some text with encoding UTF-8. Seem this library does not support UTF-8. Is it right?

Cho mình hỏi phần in bluetooth với font tiếng việt, xin hỗ trợ giúp đỡ

**Comment by AnhhoangXuan** [comment]
> i am using vietnamese. I need write some words: ư, ơ, ă, â, ứ, ớ, ở, ô, .... In this below example, i am trying write text: "Người". But receive this result. ![48377897_320304195488746_6057643520913571840_n](https://user-images.githubusercontent.com/16429671/50214736-9710ca00-03b3-11e9-95e0-f9ed41695abe.jpg)

Anh đã có giải pháp in tiếng việt chưa. ngoài in ảnh
