### ISSUE TITLE
No callback to listen for turn on of bluetooth after calling BluetoothManager.enableBluetooth()

### ISSUE THREAD

**Issue by shubhamdeol** [januslo/react-native-bluetooth-escpos-printer#9]
I am running this method **BluetoothManager.enableBluetooth()**  from componentDidMount if bluetooth enabled is false, It works fine.but, once prompt to turn bluetooth showsup and user turns on bluetooth, there is no callback which gets triggered. even code in then block of **BluetoothManager.enableBluetooth()** doesn't work

**Comment by januslo** [comment]
I am not sure how to listen the BLE Off event, any idea of that?  I are checking BLE status where It need to ensure BLE enabled,  Like scanning and printing. 

发自我的 iPhone

**Comment by shubhamdeol** [comment]
@januslo  If I am running scanDevices function,  more than one time, it falls in catch block, How did you handled connectivity issues can you please provide me some example

**Comment by januslo** [comment]
First, plz dot let use scan twice, second, what error shows while trigger scan twice?

发自我的 iPhone

**Comment by shubhamdeol** [comment]
@januslo  can you please let me know how to connect to printer using this package. I am facing problems. Sometimes it doesn't show my device in paired devices array even if the device is paired. then I need to restart the app and turn bluetooth on/off it sharts showing

**Comment by januslo** [comment]
marry Eve, plz try more about the bluetoothManager, is operation should be included in it.
You may try to listen the even rather then using the method returns, I am sorry I need to do more testing about the method returns later.

```javascript
 DeviceEventEmitter.addListener(
            BluetoothManager.EVENT_DEVICE_ALREADY_PAIRED, (rsp)=> {
                this._deviceAlreadPaired(rsp) // rsp.devices would returns the paired devices array in JSON string.
            });
        DeviceEventEmitter.addListener(
            BluetoothManager.EVENT_DEVICE_FOUND, (rsp)=> {
                this._deviceFoundEvent(rsp) // rsp.devices would returns the found device object in JSON string
            });

```

**Comment by shubhamdeol** [comment]
okay, thanks. This thing can be solved now. Can I connect to device more than once. I mean if a device is connected can I connect to it again.

or to avoid this, how can I know which device is connected to printer right now.

**Comment by januslo** [comment]
Actually, we suffer the same thing, I the last commit, I update the android connect mechanism that would check the current connect and return the connected device name directly. I one word, plz update the repo to the last one (with git url directly current, will publish a new version after this mechanism is apply and tested with IOS as well) and you can just call connect once again.

**Comment by shubhamdeol** [comment]
I tried adding these methods also, but getting these functions as undefined :(
can you fix this: here is the code 

`    @ReactMethod
    public void isDeviceConnected(Callback booleanCallback) {

        Boolean isConnected = true;

        if (mService != null) {
            switch (mService.getState()) {
                case 0:
                    isConnected = false;
                    break;

                case 2:
                    isConnected = false;
                    break;

                case 3:
                    isConnected = true;
                    break;

                default:
                    isConnected = false;
                    break;
            }
        }
        booleanCallback.invoke(isConnected);
    }



    /* Return the address of the currently connected device */
    @ReactMethod
    public void getConnectedDeviceAddress(final Promise promise) {
        if (mService!=null){
            promise.resolve(mService.getLastConnectedDeviceAddress());
        }

    }`

**Comment by januslo** [comment]
plz make sure your code was installed into node_module folder.

**Comment by shubhamdeol** [comment]
Now, I finally I am able to connect to pos printer flawlessly, Thanks for your help. Will give you a pull request soon, I have added both of these methods, which makes the connection with pos easier.
