### ISSUE TITLE
Cannot Print Turkish !

### ISSUE THREAD

**Issue by brkozdmr93** [januslo/react-native-bluetooth-escpos-printer#93]
I tried to print Turkish but it doesn't work.
I tried it : 
 await BluetoothEscposPrinter.printText("Menas\r\n", {
      encoding:'windows-1254',
      codepage:25,
      widthtimes:1,
      heigthtimes:1,
      fonttype:0
    });

but it doesn't work. How can i fix it ?

**Comment by Zhakkz** [comment]
https://github.com/januslo/react-native-bluetooth-escpos-printer/issues/66#issuecomment-594432943
