### ISSUE TITLE
TypeError: null is not an object (evaluating 'BluetoothTscPrinter.DIRECTION = {     FORWARD: 0,     BACKWARD: 1   }')

### ISSUE THREAD

**Issue by NrmeenTomoum** [januslo/react-native-bluetooth-escpos-printer#94]
TypeError: null is not an object (evaluating 'BluetoothTscPrinter.DIRECTION = {
    FORWARD: 0,
    BACKWARD: 1
  }')
iPhone

**Comment by Roen00** [comment]
I faced the same problem. Did u manage to workaround it? I run the iPhone 11 emulator.

**Comment by januslo** [comment]
Emulator would have build issue that the package cannot be installed. Plz try to use the real device to check whether problem still.

**Comment by lawrencesupiantvlk** [comment]
hi @januslo I just tried implementing the bluetooth ecpos printer in my repo. However, I face this issue as well. I run on real device(android) via expo, but still got this error. Is there some config I missed ya?

**Comment by Jerry-devblog** [comment]
same issue as above

**Comment by trongtai1801** [comment]
@januslo i try to run the demo app on real device but this error still appear. Please help, thanks.

**Comment by lyseiha** [comment]
any update yet?

**Comment by foneazmi** [comment]
same issue here, 
work well on android
but not work at ios

**Comment by vinodh622** [comment]
i'm also facing the same issue   ,any option to fix this on iphone ?

**Comment by foneazmi** [comment]
delete tsc support on ios, work for me

**Comment by vinodh622** [comment]
> delete tsc support on ios, work for me



> delete tsc support on ios, work for me

Thanks for the reply !!!  
where to find  tsc  ?

**Comment by foneazmi** [comment]
> > delete tsc support on ios, work for me
> 
> > delete tsc support on ios, work for me
> 
> Thanks for the reply !!!
> where to find tsc ?

you need to modify library code, then add to your project using modify library

**Comment by vinodh622** [comment]
please send some screenshot ,so that i can understood..

**Comment by jayanaka** [comment]
https://sochinda.wordpress.com/2020/09/02/config-januslo-react-native-bluetooth-escpos-printer-in-react-native/

**Comment by AlanWen2016** [comment]
1. add the file RNBluetoothEscposPrinter.podspec and pod install
2. replace '#import "ZXingObjC/ZXingObjC.h"' by #import "ZXingObjC.h" in RNBluetoothEscposPrinter.m

**Comment by arsyrangga** [comment]
same issue please update

**Comment by usman1579** [comment]
> Emulator would have build issue that the package cannot be installed. Plz try to use the real device to check whether problem still.

i am Using Real IOS Device but problem still Exist. Please tell me solution

**Comment by usman1579** [comment]
> > > delete tsc support on ios, work for me
> > 
> > 
> > > delete tsc support on ios, work for me
> > 
> > 
> > Thanks for the reply !!!
> > where to find tsc ?
> 
> you need to modify library code, then add to your project using modify library

can you please share the modify files

**Comment by lukasbryla** [comment]
I'm having the same problem on android. Real device, android V11, expo 42.0.0, react 16.13.1, react native sdk-42.0.0.

**Comment by chukiatt** [comment]
I test in real android device i got this error

 ERROR  Error: Requiring module "node_modules\react-native-bluetooth-escpos-printer\index.js", which threw an exception: TypeError: null is not an object (evaluating 'BluetoothTscPrinter.DIRECTION = {
    FORWARD: 0,
    BACKWARD: 1
  }')


Please help me please...


My Package.json

{
  "name": "poswarePos",
  "version": "0.0.1",
  "private": true,
  "scripts": {
    "android": "react-native run-android",
    "ios": "react-native run-ios",
    "start": "react-native start",
    "test": "jest",
    "lint": "eslint ."
  },
  "dependencies": {
    "react": "17.0.2",
    "react-native": "0.66.3",
    "react-native-bluetooth-escpos-printer": "^0.0.5"
  },
  "devDependencies": {
    "@babel/core": "7.16.0",
    "@babel/runtime": "7.16.3",
    "@react-native-community/eslint-config": "2.0.0",
    "babel-jest": "26.6.3",
    "eslint": "7.14.0",
    "jest": "26.6.3",
    "metro-react-native-babel-preset": "0.66.2",
    "react-test-renderer": "17.0.2"
  },
  "jest": {
    "preset": "react-native"
  }
}



My Settings.gradle

rootProject.name = 'poswarePos'
include ':react-native-bluetooth-escpos-printer'
project(':react-native-bluetooth-escpos-printer').projectDir = new File(rootProject.projectDir, '../node_modules/react-native-bluetooth-escpos-printer/android')
apply from: file("../node_modules/@react-native-community/cli-platform-android/native_modules.gradle"); applyNativeModulesSettingsGradle(settings)
include ':app'



My MainApplication.java

  @Override
  public void onCreate() {
    super.onCreate();
    SoLoader.init(this, /* native exopackage */ false);
    initializeFlipper(this, getReactNativeHost().getReactInstanceManager());
    new RNBluetoothEscposPrinterPackage();
  }

**Comment by chukiatt** [comment]
> Configure project :react-native-bluetooth-escpos-printer
WARNING:: Configuration 'compile' is obsolete and has been replaced with 'implementation' and 'api'.

**Comment by Elinaldo1** [comment]
> TypeError: null não é um objeto (avaliando 'BluetoothTscPrinter.DIRECTION = { FORWARD: 0, BACKWARD: 1 }') iPhone

Did anyone get a solution?
I'm running on physical android device and I can't get out of this error.

**Comment by Magnetka-dev** [comment]
Same problem here. Running on physical android device.

**Comment by RaduMirceaAndrei** [comment]
This applies to iOS in expo bare enviornment.

Install the package from github, not via npm repository.
npm install https://github.com/januslo/react-native-bluetooth-escpos-printer.git --save

In case you already installed via npm, go to your ios folder and do a:
pod deintegrate
Then go back to your root folder and install it via the github repo (above command)

As of writing this, iOS emulators do not support Bluetooth so you need a real device.

**Comment by anubhav-sri** [comment]
Still fails for me

**Comment by CorentinHeroux** [comment]
Same for me, 'BluetoothTscPrinter.DIRECTION = { FORWARD: 0, BACKWARD: 1 }'), Iphone 11 pro

**Comment by Bilel-Fitouri** [comment]
You should apply this update

https://sochinda.wordpress.com/2020/09/02/config-januslo-react-native-bluetooth-escpos-printer-in-react-native/

then pod install (that should install the RNBluetoothEscposPrinter dependency)

➜  ios git:(develop) ✗ pod install          
Auto-linking React Native modules for target `ProxiHalalOrders`: BVLinearGradient, RNBluetoothEscposPrinter, RNCAsyncStorage, RNGestureHandler, RNReanimated, RNScreens, RNSnackbar, RNVectorIcons, react-native-netinfo, react-native-safe-area-context, and react-native-version-number
Analyzing dependencies
Downloading dependencies
Installing RNBluetoothEscposPrinter (0.0.5)
Generating Pods project
Integrating client project

**Comment by jasbir-codeparking** [comment]
is this work for any one not for me
